---
- hosts: all 
  tasks:
    - name: Print message 
      debug: 
        msg: Hello Ansible World
  tasks:
    - name: Check if folder exist 
      stat:
        path: /home/ubuntu/Petclinic
      register: flag
    - name: Cloning 
      shell: |
        cd /home/ubuntu/ 
        git clone https://github.com/jaiswaladi246/Petclinic.git
      when: not flag.stat.exists
    - name: Build & Deploy
      shell: |
        cd /home/ubuntu/Petclinic 
        mvn clean package
        cp target/petclinic.war /usr/share/tomcat/webapps